### ISSUE TITLE
The Link to IoT_Router_BLE_Reference_App repository is broken 

### ISSUE THREAD

**Issue by mrsinghgit** [silverspringnetworks/developer_program#23]
The link( https://portal7-stage.mitangi.com/iot-edge-router-snappy-app ) to the “IoT Edge Router BLE Sensor Reference App” seems to be broken after changing the folder name from “IoT Router BLE” to “IoT_Router_BLE”.

Refer to the image below:

![iotr-ref-app-link](https://cloud.githubusercontent.com/assets/23510895/25504143/a3f794d8-2b51-11e7-8789-f7ff91a2db3f.jpg)

**Comment by sboorlagadda** [comment]
@mrsinghgit The link seems to be fixed now. Can you verify and close the issue?
