### ISSUE TITLE
readme not in consistent format

### ISSUE THREAD

**Issue by srinivasanramaraju** [silverspringnetworks/developer_program#4]
As the repository is public facing, we would like it to be consistent across all the code we're open sourcing.

1. It would be nice if the readme.txt could be put in the markdown format (readme.md) and avoid .txt 

2. Also, all the internal and staging url's shouldn't be exposed. 

developer_program/HDK/Milli5-Arduino CoAP Server/readme.txt

**Comment by bluben** [comment]
Agreed. I'll cobble together an outline of what we want to see and send it around to the developers. The maintainers will review them for consistency and file issues as needed. I will leave this open until I send the note around.

**Comment by abuvarp** [comment]
There is a missing letter 'l' in MilliShield. Can someone fix?

**Comment by bluben** [comment]
You can fix this. Fix it in your branch and commit the change. Ask for a pull and I’ll merge it.


- Bob

**Comment by bluben** [comment]
Minor changes have improved this. An internal effort is underway to improve the README files.
